apiVersion: v1
kind: Service
metadata:
  name: fsa-fe
  namespace: app
  labels:
    app: fsa-fe
spec:
  selector:
    app: fsa-fe
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
  # loadBalancerIP: "52.138.207.76"
