version: '3.1'

services:
  windat_db:
    image: postgres
    restart: always
    ports:
      - "6969:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: windat_db
    volumes:
      - windat_db_disk:/var/lib/postgresql/data
volumes:
  windat_db_disk:
    driver: local