spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8082/realms/WinDat
#          jwk-set-uri: http://localhost:8082/realms/WinDat/protocol/openid-connect/certs
#  datasource:
#    url: jdbc:postgresql://localhost:6969/windat_db
#    username: admin
#    password: admin
#    driver-class-name: org.postgresql.Driver
#    name: windat_db
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    mapping-resources:
      - persistence/orm.xml
# Kubernetes probes (readiness & liveness) and monitoring
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

keycloak:
# Production URL
  auth-server-url: http://4.245.186.27/auth
  realm: WinDat
  admin-cli:
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}

rewards:
  leaderboard:
    top-players-count: 10
    prizes:
#      50000 credits for 1st
      1st-place: 50000
      2nd-place: 30000
      3rd-place: 20000
      4th-place: 10000
      5th-place: 7500
      6th-place: 5000
      7th-place: 2500
      8th-place: 1000
      9th-place: 500
      10th-place: 250