spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8082/realms/WinDat
#          jwk-set-uri: http://localhost:8082/realms/WinDat/protocol/openid-connect/certs
#  datasource:
#    url: jdbc:postgresql://localhost:6969/windat_db
#    username: admin
#    password: admin
#    driver-class-name: org.postgresql.Driver
#    name: windat_db
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    mapping-resources:
      - persistence/orm.xml
# Kubernetes probes (readiness & liveness) and monitoring
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

keycloak:
#  Change this url in production
  auth-server-url: http://localhost:8082
  realm: WinDat
  admin-cli:
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}